// SEO 选题库 - 围绕轩宇汇（Temu 半托管 POD 一件代发分销中台）的长尾词矩阵
// 每次生成时随机选取一个未使用的选题，调用 AI 生成原创文章
module.exports = {
  // 站点基础信息（生成文章内链、CTA 时使用）
  site: {
    name: '轩宇汇',
    url: 'https://www.pod.ddddnet.cn',
    appUrl: 'https://pod.ddddnet.cn',
    desc: 'Temu半托管POD一件代发分销中台',
  },
  // 选题列表：topic=主题方向, keywords=SEO关键词, category=分类
  topics: [
    // ===== Temu 半托管代发 =====
    { topic: 'Temu半托管一件代发完整流程教程', keywords: ['Temu半托管', '一件代发', '代发流程'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管卖家如何零库存创业', keywords: ['Temu半托管', '零库存', '卖家创业'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管代发平台怎么选', keywords: ['Temu代发', '代发平台', '半托管'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管自动拉单教程', keywords: ['Temu拉单', '自动拉单', '半托管'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管多区域店铺管理(125/225/325/525)', keywords: ['Temu多区域', '125', '225', '半托管'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管订单自动推单工厂', keywords: ['Temu推单', '推单工厂', '代发'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管物流回传怎么设置', keywords: ['Temu物流回传', '运单号', '半托管'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管代发利润怎么算', keywords: ['Temu代发', '利润计算', '货品价差'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管白标绑店教程', keywords: ['Temu绑店', '白标', '半托管'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管代发避坑指南', keywords: ['Temu代发', '避坑', '半托管'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管和全托管能做代发吗', keywords: ['Temu半托管', '全托管', '代发'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管新手开店到代发全流程', keywords: ['Temu新手', '代发全流程', '半托管'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管代发平台对比', keywords: ['Temu代发', '平台对比', '工具'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管代发模式售后怎么处理', keywords: ['Temu售后', '代发售后', '半托管'], category: 'Temu半托管代发' },

    // ===== POD 一件代发 =====
    { topic: 'POD一件代发是什么', keywords: ['POD', '一件代发', '按需印刷'], category: 'POD一件代发' },
    { topic: 'POD按需印刷代发模式解析', keywords: ['POD', '按需印刷', '代发模式'], category: 'POD一件代发' },
    { topic: 'POD代发如何对接工厂', keywords: ['POD代发', '对接工厂', '供应链'], category: 'POD一件代发' },
    { topic: 'POD图案代发全流程', keywords: ['POD图案', '代发流程', '印花'], category: 'POD一件代发' },
    { topic: 'POD代发生意怎么起步', keywords: ['POD代发', '创业起步', '零库存'], category: 'POD一件代发' },
    { topic: 'POD代发平台推荐', keywords: ['POD代发', '平台推荐', '工具'], category: 'POD一件代发' },
    { topic: 'POD代发利润空间分析', keywords: ['POD代发', '利润', '价差'], category: 'POD一件代发' },
    { topic: 'POD定制商品代发教程', keywords: ['POD定制', '代发教程', '商品'], category: 'POD一件代发' },
    { topic: 'POD代发避免版权侵权', keywords: ['POD代发', '版权侵权', '规避'], category: 'POD一件代发' },
    { topic: 'POD代发货源哪里找', keywords: ['POD代发', '货源', '工厂'], category: 'POD一件代发' },
    { topic: 'POD代发和自发货区别', keywords: ['POD代发', '自发货', '区别'], category: 'POD一件代发' },
    { topic: 'POD代发适合新手吗', keywords: ['POD代发', '新手', '适合'], category: 'POD一件代发' },
    { topic: 'POD印花代发注意事项', keywords: ['POD印花', '代发', '注意事项'], category: 'POD一件代发' },
    { topic: 'POD代发自动化流程搭建', keywords: ['POD代发', '自动化', '流程'], category: 'POD一件代发' },

    // ===== 分销中台 / 供应链 =====
    { topic: '什么是POD分销中台', keywords: ['分销中台', 'POD', '代发系统'], category: '分销中台' },
    { topic: '分销中台如何对接上游工厂', keywords: ['分销中台', '对接工厂', 'OpenAPI'], category: '分销中台' },
    { topic: '代发分销系统架构解析', keywords: ['代发系统', '架构', '分销'], category: '分销中台' },
    { topic: '多租户分销中台是什么', keywords: ['多租户', '分销中台', '隔离'], category: '分销中台' },
    { topic: '分销中台SKU映射怎么做', keywords: ['SKU映射', '分销中台', '代发'], category: '分销中台' },
    { topic: '供应链分销中台选型', keywords: ['供应链', '分销中台', '选型'], category: '分销中台' },
    { topic: '代发系统的订单审核流设计', keywords: ['代发', '订单审核', '资金'], category: '分销中台' },
    { topic: '分销中台如何做资金结算', keywords: ['分销中台', '资金结算', '余额'], category: '分销中台' },
    { topic: '分销中台白标模式解析', keywords: ['分销中台', '白标', '隐身'], category: '分销中台' },
    { topic: '代发中台如何保证数据隔离', keywords: ['代发', '数据隔离', '多租户'], category: '分销中台' },
    { topic: '分销中台对接工厂OpenAPI', keywords: ['分销中台', '工厂', 'OpenAPI'], category: '分销中台' },
    { topic: '工厂直供分销中台搭建', keywords: ['工厂直供', '分销中台', '搭建'], category: '分销中台' },
    { topic: '分销中台邮件提醒通知', keywords: ['分销中台', '邮件提醒', '通知'], category: '分销中台' },
    { topic: '分销中台与ERP区别', keywords: ['分销中台', 'ERP', '区别'], category: '分销中台' },

    // ===== 选品与运营 =====
    { topic: 'Temu半托管代发选品技巧', keywords: ['Temu代发', '选品技巧', '半托管'], category: '选品运营' },
    { topic: '代发模式高利润品类', keywords: ['代发', '高利润', '品类'], category: '选品运营' },
    { topic: 'POD代发选品方法论', keywords: ['POD代发', '选品', '方法论'], category: '选品运营' },
    { topic: '代发卖家如何定售价', keywords: ['代发', '定价', '售价'], category: '选品运营' },
    { topic: '代发店铺如何提升转化', keywords: ['代发', '转化率', '店铺'], category: '选品运营' },
    { topic: '代发模式爆款挖掘', keywords: ['代发', '爆款', '挖掘'], category: '选品运营' },
    { topic: 'Temu代发新品流量获取', keywords: ['Temu代发', '新品流量', '半托管'], category: '选品运营' },
    { topic: '代发卖家数据分析指标', keywords: ['代发', '数据分析', '指标'], category: '选品运营' },
    { topic: '代发店铺主图规范', keywords: ['代发', '主图', '规范'], category: '选品运营' },
    { topic: '代发商品详情页优化', keywords: ['代发', '详情页', '优化'], category: '选品运营' },
    { topic: '代发店铺活动报名', keywords: ['代发', '活动报名', 'Temu'], category: '选品运营' },
    { topic: '代发模式库存怎么管(零库存)', keywords: ['代发', '零库存', '库存'], category: '选品运营' },
    { topic: '代发卖家竞品分析', keywords: ['代发', '竞品分析', '卖家'], category: '选品运营' },
    { topic: '代发店铺评分维护', keywords: ['代发', '评分维护', '店铺'], category: '选品运营' },

    // ===== 白标 / 品牌 =====
    { topic: '什么是白标代发模式', keywords: ['白标', '代发', '模式'], category: '白标品牌' },
    { topic: '白标分销如何隐藏上游', keywords: ['白标', '隐藏上游', '分销'], category: '白标品牌' },
    { topic: '白标模式品牌归谁', keywords: ['白标', '品牌', '归属'], category: '白标品牌' },
    { topic: '白标代发平台搭建', keywords: ['白标', '代发平台', '搭建'], category: '白标品牌' },
    { topic: '白标模式顾客体验', keywords: ['白标', '顾客体验', '代发'], category: '白标品牌' },
    { topic: '白标分销合规要点', keywords: ['白标', '合规', '分销'], category: '白标品牌' },
    { topic: '白标代发和自营区别', keywords: ['白标', '自营', '区别'], category: '白标品牌' },
    { topic: '白标模式如何做客服', keywords: ['白标', '客服', '代发'], category: '白标品牌' },
    { topic: '白标代发信任建设', keywords: ['白标', '信任', '代发'], category: '白标品牌' },
    { topic: '白标分销利润分成', keywords: ['白标', '利润分成', '分销'], category: '白标品牌' },
    { topic: '白标代发风险控制', keywords: ['白标', '风险', '控制'], category: '白标品牌' },
    { topic: '白标模式多店铺管理', keywords: ['白标', '多店铺', '管理'], category: '白标品牌' },
    { topic: '白标代发合同与授权', keywords: ['白标', '合同', '授权'], category: '白标品牌' },
    { topic: '白标分销未来趋势', keywords: ['白标', '趋势', '分销'], category: '白标品牌' },

    // ===== 跨境干货 =====
    { topic: '跨境代发平台对比', keywords: ['跨境代发', '平台对比', '工具'], category: '跨境干货' },
    { topic: '一件代发跨境电商入门', keywords: ['一件代发', '跨境电商', '入门'], category: '跨境干货' },
    { topic: '跨境代发收款方案', keywords: ['跨境代发', '收款', '支付'], category: '跨境干货' },
    { topic: '跨境代发支付与结算', keywords: ['跨境代发', '支付', '结算'], category: '跨境干货' },
    { topic: '跨境代发多店铺管理', keywords: ['跨境代发', '多店铺', '管理'], category: '跨境干货' },
    { topic: '跨境代发退货处理', keywords: ['跨境代发', '退货', '售后'], category: '跨境干货' },
    { topic: '跨境代发税务要点', keywords: ['跨境代发', '税务', '合规'], category: '跨境干货' },
    { topic: '跨境代发物流模式', keywords: ['跨境代发', '物流', '模式'], category: '跨境干货' },
    { topic: '跨境代发独立站vs平台', keywords: ['跨境代发', '独立站', '平台'], category: '跨境干货' },
    { topic: '跨境代发新手起步', keywords: ['跨境代发', '新手', '起步'], category: '跨境干货' },
    { topic: '跨境代发选品工具', keywords: ['跨境代发', '选品工具', 'SaaS'], category: '跨境干货' },
    { topic: '跨境代发供应链搭建', keywords: ['跨境代发', '供应链', '搭建'], category: '跨境干货' },
    { topic: '跨境代发SaaS工具', keywords: ['跨境代发', 'SaaS', '工具'], category: '跨境干货' },
    { topic: '跨境代发行业报告', keywords: ['跨境代发', '行业报告', '趋势'], category: '跨境干货' },

    // ===== 行业趋势 =====
    { topic: '2026跨境电商代发趋势', keywords: ['跨境电商', '代发趋势', '2026'], category: '行业趋势' },
    { topic: 'POD代发市场前景', keywords: ['POD代发', '市场前景', '按需印刷'], category: '行业趋势' },
    { topic: 'Temu半托管代发机会', keywords: ['Temu半托管', '代发机会', '跨境'], category: '行业趋势' },
    { topic: '一件代发还能做吗2026', keywords: ['一件代发', '2026', '还能做吗'], category: '行业趋势' },
    { topic: '跨境代发自动化趋势', keywords: ['跨境代发', '自动化', '趋势'], category: '行业趋势' },
    { topic: '白标分销会成为主流吗', keywords: ['白标分销', '主流', '趋势'], category: '行业趋势' },
    { topic: '代发模式监管与合规', keywords: ['代发', '监管', '合规'], category: '行业趋势' },
    { topic: '跨境供应链数字化', keywords: ['跨境', '供应链', '数字化'], category: '行业趋势' },
    { topic: '代发卖家出海机遇', keywords: ['代发', '出海', '机遇'], category: '行业趋势' },
    { topic: 'POD按需印刷市场', keywords: ['POD', '按需印刷', '市场'], category: '行业趋势' },
  ],
};
