// SEO 选题库 - 围绕轩宇汇（Temu 半托管 POD 美国源头工厂货盘）的长尾词矩阵
// 核心叙事：用轩宇汇美国工厂的现成 POD 货盘（服装/T恤、水杯/马克杯等），零库存、一件代发、无资金压力，把货卖向全球
// 每次生成时随机选取一个未使用的选题，调用 AI 生成原创文章
module.exports = {
  // 站点基础信息（生成文章内链、CTA 时使用）
  site: {
    name: '轩宇汇',
    url: 'https://www.pod.ddddnet.cn',
    appUrl: 'https://pod.ddddnet.cn',
    desc: 'Temu半托管POD美国源头工厂货盘',
  },
  // 选题列表：topic=主题方向, keywords=SEO关键词, category=分类
  topics: [
    // ===== POD 货盘卖货（主推叙事：服装/水杯、零库存、一件代发、全球卖货）=====
    { topic: 'POD服装一件代发怎么卖货', keywords: ['POD服装', '一件代发', 'T恤卖货'], category: 'POD货盘卖货' },
    { topic: 'POD马克杯水杯怎么做跨境卖货', keywords: ['POD水杯', '马克杯', '跨境卖货'], category: 'POD货盘卖货' },
    { topic: '零库存做POD把货卖全球真的能赚吗', keywords: ['零库存', 'POD卖全球', '赚差价'], category: 'POD货盘卖货' },
    { topic: '无资金压力起步POD副业卖货', keywords: ['无资金压力', 'POD副业', '轻创业'], category: 'POD货盘卖货' },
    { topic: '用轩宇汇美国工厂货盘开店卖货', keywords: ['轩宇汇美国工厂', '货盘开店', 'POD'], category: 'POD货盘卖货' },
    { topic: 'POD货盘选品：服装还是水杯', keywords: ['POD货盘', '服装选品', '水杯选品'], category: 'POD货盘卖货' },
    { topic: 'Temu半托管上架POD货品卖货', keywords: ['Temu半托管', 'POD上架', '货品卖货'], category: 'POD货盘卖货' },
    { topic: 'POD一件代发和传统备货哪个风险小', keywords: ['一件代发', '传统备货', '库存风险'], category: 'POD货盘卖货' },
    { topic: '新手做POD服装从0到出单', keywords: ['新手POD', '服装出单', 'T恤'], category: 'POD货盘卖货' },
    { topic: 'POD水杯马克杯爆款怎么找', keywords: ['POD水杯', '爆款', '马克杯'], category: 'POD货盘卖货' },
    { topic: '全球卖货POD物流怎么解决', keywords: ['全球卖货', 'POD物流', '代发'], category: 'POD货盘卖货' },
    { topic: 'POD图案设计怎么帮卖货', keywords: ['POD设计', '卖货', '图案'], category: 'POD货盘卖货' },
    { topic: 'POD零成本测款上架卖货', keywords: ['POD测款', '零成本', '上架'], category: 'POD货盘卖货' },
    { topic: '2026用现成货盘做POD还有机会吗', keywords: ['2026', 'POD货盘', '机会'], category: 'POD货盘卖货' },

    // ===== Temu 半托管代发 =====
    { topic: 'Temu半托管一件代发完整流程教程', keywords: ['Temu半托管', '一件代发', '代发流程'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管卖家如何零库存创业', keywords: ['Temu半托管', '零库存', '卖家创业'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管代发平台怎么选', keywords: ['Temu代发', '代发平台', '半托管'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管自动拉单教程', keywords: ['Temu拉单', '自动拉单', '半托管'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管多区域店铺管理(125/225/325/525)', keywords: ['Temu多区域', '125', '225', '半托管'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管订单自动推单工厂', keywords: ['Temu推单', '推单工厂', '代发'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管物流回传怎么设置', keywords: ['Temu物流回传', '运单号', '半托管'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管代发利润怎么算', keywords: ['Temu代发', '利润计算', '货品价差'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管代发避坑指南', keywords: ['Temu代发', '避坑', '半托管'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管和全托管能做代发吗', keywords: ['Temu半托管', '全托管', '代发'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管新手开店到代发全流程', keywords: ['Temu新手', '代发全流程', '半托管'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管代发平台对比', keywords: ['Temu代发', '平台对比', '工具'], category: 'Temu半托管代发' },
    { topic: 'Temu半托管代发模式售后怎么处理', keywords: ['Temu售后', '代发售后', '半托管'], category: 'Temu半托管代发' },

    // ===== POD 一件代发 =====
    { topic: 'POD一件代发是什么', keywords: ['POD', '一件代发', '按需印刷'], category: 'POD一件代发' },
    { topic: 'POD按需印刷代发模式解析', keywords: ['POD', '按需印刷', '代发模式'], category: 'POD一件代发' },
    { topic: 'POD代发如何选源头工厂', keywords: ['POD代发', '源头工厂', '供应链'], category: 'POD一件代发' },
    { topic: 'POD图案代发全流程', keywords: ['POD图案', '代发流程', '印花'], category: 'POD一件代发' },
    { topic: 'POD代发生意怎么起步', keywords: ['POD代发', '创业起步', '零库存'], category: 'POD一件代发' },
    { topic: 'POD代发平台推荐', keywords: ['POD代发', '平台推荐', '工具'], category: 'POD一件代发' },
    { topic: 'POD代发利润空间分析', keywords: ['POD代发', '利润', '价差'], category: 'POD一件代发' },
    { topic: 'POD定制商品代发教程', keywords: ['POD定制', '代发教程', '商品'], category: 'POD一件代发' },
    { topic: 'POD代发避免版权侵权', keywords: ['POD代发', '版权侵权', '规避'], category: 'POD一件代发' },
    { topic: 'POD代发货源哪里找', keywords: ['POD代发', '货源', '工厂'], category: 'POD一件代发' },
    { topic: 'POD代发和自发货区别', keywords: ['POD代发', '自发货', '区别'], category: 'POD一件代发' },
    { topic: 'POD代发适合新手吗', keywords: ['POD代发', '新手', '适合'], category: 'POD一件代发' },
    { topic: 'POD印花代发注意事项', keywords: ['POD印花', '代发', '注意事项'], category: 'POD一件代发' },
    { topic: 'POD代发自动化流程搭建', keywords: ['POD代发', '自动化', '流程'], category: 'POD一件代发' },

    // ===== 美国源头工厂直供 =====
    { topic: '轩宇汇美国源头工厂货盘解析', keywords: ['美国源头工厂', '货盘', '轩宇汇'], category: '美国源头工厂直供' },
    { topic: '美国工厂直供一件代发流程', keywords: ['美国工厂直供', '一件代发', '流程'], category: '美国源头工厂直供' },
    { topic: '源头工厂怎么保证POD品质', keywords: ['源头工厂', 'POD品质', '质检'], category: '美国源头工厂直供' },
    { topic: '工厂货盘SKU映射怎么做', keywords: ['工厂货盘', 'SKU映射', '代发'], category: '美国源头工厂直供' },
    { topic: '美国工厂直供订单审核流', keywords: ['美国工厂', '订单审核', '直供'], category: '美国源头工厂直供' },
    { topic: '源头工厂资金结算方式', keywords: ['源头工厂', '资金结算', '货款'], category: '美国源头工厂直供' },
    { topic: '工厂直供货盘售后怎么处理', keywords: ['工厂直供', '货盘售后', '退货'], category: '美国源头工厂直供' },
    { topic: '源头工厂多区域发货(125/225/325/525)', keywords: ['源头工厂', '多区域', 'Temu区域'], category: '美国源头工厂直供' },
    { topic: '美国工厂POD物流回传时效', keywords: ['美国工厂', 'POD物流', '回传时效'], category: '美国源头工厂直供' },
    { topic: '工厂货盘与平台代发区别', keywords: ['工厂货盘', '平台代发', '区别'], category: '美国源头工厂直供' },
    { topic: '源头工厂如何管理库存风险', keywords: ['源头工厂', '库存风险', '零库存'], category: '美国源头工厂直供' },
    { topic: '美国工厂直供价格优势', keywords: ['美国工厂', '价格优势', '直供'], category: '美国源头工厂直供' },
    { topic: '工厂货盘如何支持全球卖货', keywords: ['工厂货盘', '全球卖货', '直发'], category: '美国源头工厂直供' },

    // ===== 选品与运营 =====
    { topic: 'Temu半托管代发选品技巧', keywords: ['Temu代发', '选品技巧', '半托管'], category: '选品运营' },
    { topic: '代发模式高利润品类', keywords: ['代发', '高利润', '品类'], category: '选品运营' },
    { topic: 'POD代发选品方法论', keywords: ['POD代发', '选品', '方法论'], category: '选品运营' },
    { topic: '代发卖家如何定售价', keywords: ['代发', '定价', '售价'], category: '选品运营' },
    { topic: '代发店铺如何提升转化', keywords: ['代发', '转化率', '店铺'], category: '选品运营' },
    { topic: '代发模式爆款挖掘', keywords: ['代发', '爆款', '挖掘'], category: '选品运营' },
    { topic: 'Temu代发新品流量获取', keywords: ['Temu代发', '新品流量', '半托管'], category: '选品运营' },
    { topic: '代发卖家数据分析指标', keywords: ['代发', '数据分析', '指标'], category: '选品运营' },
    { topic: '代发店铺主图规范', keywords: ['代发', '主图', '规范'], category: '选品运营' },
    { topic: '代发商品详情页优化', keywords: ['代发', '详情页', '优化'], category: '选品运营' },
    { topic: '代发店铺活动报名', keywords: ['代发', '活动报名', 'Temu'], category: '选品运营' },
    { topic: '代发模式库存怎么管(零库存)', keywords: ['代发', '零库存', '库存'], category: '选品运营' },
    { topic: '代发卖家竞品分析', keywords: ['代发', '竞品分析', '卖家'], category: '选品运营' },
    { topic: '代发店铺评分维护', keywords: ['代发', '评分维护', '店铺'], category: '选品运营' },


    // ===== 跨境干货 =====
    { topic: '跨境代发平台对比', keywords: ['跨境代发', '平台对比', '工具'], category: '跨境干货' },
    { topic: '一件代发跨境电商入门', keywords: ['一件代发', '跨境电商', '入门'], category: '跨境干货' },
    { topic: '跨境代发收款方案', keywords: ['跨境代发', '收款', '支付'], category: '跨境干货' },
    { topic: '跨境代发支付与结算', keywords: ['跨境代发', '支付', '结算'], category: '跨境干货' },
    { topic: '跨境代发多店铺管理', keywords: ['跨境代发', '多店铺', '管理'], category: '跨境干货' },
    { topic: '跨境代发退货处理', keywords: ['跨境代发', '退货', '售后'], category: '跨境干货' },
    { topic: '跨境代发税务要点', keywords: ['跨境代发', '税务', '合规'], category: '跨境干货' },
    { topic: '跨境代发物流模式', keywords: ['跨境代发', '物流', '模式'], category: '跨境干货' },
    { topic: '跨境代发独立站vs平台', keywords: ['跨境代发', '独立站', '平台'], category: '跨境干货' },
    { topic: '跨境代发新手起步', keywords: ['跨境代发', '新手', '起步'], category: '跨境干货' },
    { topic: '跨境代发选品工具', keywords: ['跨境代发', '选品工具', 'SaaS'], category: '跨境干货' },
    { topic: '跨境代发供应链搭建', keywords: ['跨境代发', '供应链', '搭建'], category: '跨境干货' },
    { topic: '跨境代发SaaS工具', keywords: ['跨境代发', 'SaaS', '工具'], category: '跨境干货' },
    { topic: '跨境代发行业报告', keywords: ['跨境代发', '行业报告', '趋势'], category: '跨境干货' },

    // ===== 行业趋势 =====
    { topic: '2026跨境电商代发趋势', keywords: ['跨境电商', '代发趋势', '2026'], category: '行业趋势' },
    { topic: 'POD代发市场前景', keywords: ['POD代发', '市场前景', '按需印刷'], category: '行业趋势' },
    { topic: 'Temu半托管代发机会', keywords: ['Temu半托管', '代发机会', '跨境'], category: '行业趋势' },
    { topic: '一件代发还能做吗2026', keywords: ['一件代发', '2026', '还能做吗'], category: '行业趋势' },
    { topic: '跨境代发自动化趋势', keywords: ['跨境代发', '自动化', '趋势'], category: '行业趋势' },
    { topic: '代发模式监管与合规', keywords: ['代发', '监管', '合规'], category: '行业趋势' },
    { topic: '跨境供应链数字化', keywords: ['跨境', '供应链', '数字化'], category: '行业趋势' },
    { topic: '代发卖家出海机遇', keywords: ['代发', '出海', '机遇'], category: '行业趋势' },
    { topic: 'POD按需印刷市场', keywords: ['POD', '按需印刷', '市场'], category: '行业趋势' },
  ],
};
